ContactsApp/Models/ChangePassword.cs
using System.ComponentModel.DataAnnotations;

namespace ContactsApp.Models {
    public class ChangePassword {
        public int Id { get; set; }
        [Required(ErrorMessage = "Enter current user password")]
        public string CurrentPassword { get; set; }
        [Required(ErrorMessage = "Enter new user password")]
        public string NewPassword { get; set;}
        [Required(ErrorMessage = "Confirm the user's new password")]
        [Compare("NewPassword", ErrorMessage = "Password doesn't match")]
        public string ConfirmNewPassword { get; set;}

    }
}

ContactsApp/Controllers/ChangePasswordController.cs
using ContactsApp.Helpers;
using ContactsApp.Models;
using ContactsApp.Repos.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ContactsApp.Controllers {
    public class ChangePasswordController : Controller {
        private readonly IUserRepos _userRepos;
        private readonly ISessionTemp _sessionTemp;

        public ChangePasswordController(IUserRepos userRepos, ISessionTemp sessionTemp) {
            _userRepos=userRepos;
            _sessionTemp= sessionTemp;
        }

        public IActionResult Index() {
            return View();
        }

        [HttpPost]
        public IActionResult Change(ChangePassword changePassword) {
            try {
                User userLogged = _sessionTemp.GetUserSession();
                changePassword.Id = userLogged.Id;
                if (ModelState.IsValid) {
                    _userRepos.ChangePwd(changePassword);
                    TempData["SuccessMessage"] = "Password changed successfully";
                    return View("Index", changePassword);
                }
                return View("Index", changePassword);
            }
            catch (Exception e) {
                TempData["ErrorMessage"] = $"Oops, error changing your password, try again. Error: {e.Message}";
                return View("Index", changePassword);
            }
        }
    }
}

ContactsApp/Views/ChangePassword/Index.cshtml
@model ChangePassword
@{
    ViewData["Title"] = "Change user password";
}

@if (TempData["SuccessMessage"] != null) {
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
        @TempData["SuccessMessage"]
    </div>
}
@if (TempData["ErrorMessage"] != null) {
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
        @TempData["ErrorMessage"]
    </div>
}

<div class="text-center">
    <h1 class="display-4">Change user password</h1>
</div>

<form asp-controller="ChangePassword" asp-action="Change" method="post">
    <div class="form-group">
        <label for="currentPassword">Current Password</label>
        <input type="password" asp-for="CurrentPassword" class="form-control" placeholder="Enter current user password">
        @Html.ValidationMessageFor(x => x.CurrentPassword)
    </div>
    <div class="form-group">
        <label for="newPassword">New Password</label>
        <input type="password" asp-for="NewPassword" class="form-control" placeholder="Enter a new user password">
        @Html.ValidationMessageFor(x => x.NewPassword)
    </div>
    <div class="form-group">
        <label for="confirmNewPassword">Confirm New Password</label>
        <input type="password" asp-for="ConfirmNewPassword" class="form-control" placeholder="Confirm new user password">
        @Html.ValidationMessageFor(x => x.ConfirmNewPassword)
    </div>

    <br />
    <button type="submit" class="btn btn-primary col-12 mb-1">Change</button>
    <a class="btn btn-secondary col-12" asp-controller="Home" asp-action="Index" role="button">Back</a>
</form>